Add "string not blank when trimmed" validator
sovity/authority-portal pull request #217
Opened 2024-06-04 06:20 UTC by illfixit

_What issues does this PR close?_
closes #193 Error message vague for various validation issues on CaaS request 

```[tasklist]
### Checklist
- [ ] The PR title is short and expressive.
- [ ] I have updated the CHANGELOG.md. See [changelog_update.md](https://github.com/sovity/authority-portal/tree/main/docs/dev/changelog_updates.md) for more information.
- [ ] I have updated the Deployment Migration Notes Section in the CHANGELOG.md for any configuration / external API changes.
- [ ] I have performed a **self-review**
```

2024-06-04 16:30 UTC, kamilczaja requested changes

2024-06-04 16:30 UTC, kamilczaja commented on CHANGELOG.md
> +- Fix not handling whitespaces as text fields input [#193](https://github.com/sovity/authority-portal/issues/193)
```suggestion
- Input fields containing only whitespaces are now properly validated and an appropriate error message is shown [#193](https://github.com/sovity/authority-portal/issues/193)
```

2024-06-04 16:30 UTC, kamilczaja commented on authority-portal-frontend/src/app/common/components/form-elements/text-input/text-input.component.html
> +  class="w-full min-h-fit text-s"
_comment: Can you explain real quick why you changed this?_

2024-06-04 16:30 UTC, kamilczaja commented on authority-portal-frontend/src/app/common/components/form-elements/text-input/text-input.component.html
_comment: I'm sure it doesn't change anything but why did you add white background to the material error messages? The background is white anyway and this will probably break if we ever implement a dark-mode or something like that_

2024-06-05 12:34 UTC, richardtreier approved these changes
LGTM

2024-06-05 12:53 UTC, kamilczaja requested changes

2024-06-05 12:53 UTC, kamilczaja commented on authority-portal-frontend/src/app/common/components/form-elements/text-input/text-input.component.html
Aren't those `bg-white` now redundant after you fixed this with the CSS approach?

2024-06-05 12:54 UTC, illfixit commented on authority-portal-frontend/src/app/common/components/form-elements/text-input/text-input.component.html
they're removed, you look at the old version :)

2024-06-05 12:57 UTC, merged