Broker Merger
sovity/authority-portal pull request #218
Opened 2024-06-05 11:48 UTC by kamilczaja

_What issues does this PR close?_

```[tasklist]
### Checklist
- [ ] The PR title is short and expressive.
- [ ] I have updated the CHANGELOG.md. See [changelog_update.md](https://github.com/sovity/authority-portal/tree/main/docs/dev/changelog_updates.md) for more information.
- [ ] I have updated the Deployment Migration Notes Section in the CHANGELOG.md for any configuration / external API changes.
- [ ] I have performed a **self-review**
```

2024-06-26 16:44 UTC, kamilczaja commented on authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/auth/ConfigApiKeyFilter.kt
My impression is that this file is unused.
A comment in `ConfigResourceImpl.kt` is saying that this is handling the auth for config endpoints via API Key but I wasn't able to find a reference in code. Could you take a look at it @richardtreier ?

2024-07-02 10:22 UTC, richardtreier requested changes

2024-07-02 10:22 UTC, richardtreier commented on old-tests/integration/pages/organizationmanagement/OrganizationInfoApiServiceTest.kt
> +    // TODO Fix test
todo

2024-07-02 10:22 UTC, richardtreier commented on old-tests/integration/pages/organizationmanagement/OrganizationInfoApiServiceTest.kt
> +    // TODO Fix test
todo

2024-07-02 11:11 UTC, richardtreier commented on CHANGELOG.md
> +  - Removed the Data Catalog status data from the system stability report
moved to https://github.com/sovity/PMO-Software/issues/1261

2024-07-02 11:14 UTC, richardtreier commented on CHANGELOG.md
> +  - Removed the link to "My data offers" from the sidebar. Due to the integration of the Data Catalog, this feature is not supported for now.
moved to https://github.com/sovity/PMO-Software/issues/1261

2024-07-02 11:14 UTC, richardtreier commented on CHANGELOG.md
> +      authority-portal.deployment.environments.{environmentId}.broker.kuma-name
moved to https://github.com/sovity/PMO-Software/issues/1261

2024-07-02 11:31 UTC, richardtreier commented on old-tests/integration/pages/organizationmanagement/OrganizationInfoApiServiceTest.kt
> +    // TODO Fix test
https://github.com/sovity/PMO-Software/issues/1261

2024-07-02 11:53 UTC, richardtreier commented on authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/auth/ConfigApiKeyFilter.kt
i think it's in use

2024-07-02 11:55 UTC, richardtreier approved these changes
all further stuff will be done as separate PRs

2024-07-02 11:56 UTC, merged