Redirect to original URL after login
sovity/authority-portal pull request #244
Opened 2024-07-22 14:34 UTC by illfixit

_What issues does this PR close?_

```[tasklist]
### Checklist
- [x] The PR title is short and expressive.
- [x] I have updated the CHANGELOG.md. See [changelog_update.md](https://github.com/sovity/authority-portal/tree/main/docs/dev/changelog_updates.md) for more information.
- [ ] I have updated the Deployment Migration Notes Section in the CHANGELOG.md for any configuration / external API changes.
- [x] I have performed a **self-review**
```

2024-07-23 07:42 UTC, illfixit commented on authority-portal-frontend/src/app/core/global-state/routes/url-before-login.service.ts
> +
```suggestion
int test = "hello Suggestion"
```

2024-07-24 15:54 UTC, richardtreier commented
closed in favor of https://github.com/sovity/authority-portal/pull/247

2024-08-12 12:55 UTC, kamilczaja requested changes

2024-08-12 12:55 UTC, kamilczaja commented on authority-portal-frontend/src/app/app-routing.module.ts
> +  })(),
DRY

2024-08-12 15:43 UTC, kamilczaja approved these changes
LGTM

2024-08-12 15:43 UTC, merged